server:
   port: 8088
   
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/bcp_server_c?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      
mybatis:
   type-aliases-package: com.bcp.serverc.mapper
   # 不配置这个mapper中自定义的sql无法绑定
   mapper-locations: classpath*:/mapper/*.xml
   configuration:
    # 进行自动映射时，数据以下划线命名，如数据库返回的"order_address"命名字段是否映射为class的"orderAddress"字段。默认为false
      map-underscore-to-camel-case: true

# 打印sql执行
logging:
   level:
     com.bcp.serverc.mapper : debug